### ISSUE TITLE
New Listings - deep link filters

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1022]
We need to have the filters deep linked.  So, I should be able to construct a URL to a filtered challenge list with any combination of valid filters.

**Comment by birdofpreyru** [comment]
Done. Though, probably you won't like the way serialization is done: it does not produce a human-readable addition to URL. I've implemented filters as a hierarchy of filter classes (i.e. each class extends its parent adding to it additional filtering necessary for this very component, so that resulting hierarchy matches the hierarchy of UI components we use for filtering). So, each class in the hierarchy serializes itself into JSON object, encodes it into base64, and passes the result to its child class, which is free to append anything necessary to store its state.

Sure, serialization can be re-worked without touching anything else.
