### ISSUE TITLE
Code challenge with data science background

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1109]
On production listing, we have a code/background mismatch. The challenge is code, but is orange as data science. The challenge is also TCO eligible and that code is green (code). They should match. Look at https://www.topcoder.com/listings/

Expected:
![screen shot 53](https://cloud.githubusercontent.com/assets/8484061/24479665/36ecc50c-1495-11e7-8ed5-4ec512ec459f.png)

Rendered:
![screen shot 52](https://cloud.githubusercontent.com/assets/8484061/24479674/3be0ccd4-1495-11e7-9955-13583b0ed9df.png)

**Comment by ThomasKranitsas** [comment]
@vic-topcoder actually the icon is orange because the challenge has the `Data Science` keyword.
So the expected image you posted above is not quite correct. I guess the correct fix here should be to change the TCO badge to orange if the challenge has the `Data Science` keyword.

Can you please confirm this? Thanks

**Comment by ThomasKranitsas** [comment]
The 'expected' image above has the MM abbreviation that's why I'm saying it's not correct... It should still have the correct abbreviation (eg `Cd`), right?

**Comment by vic-topcoder** [comment]
@ThomasKranitsas yes, the thing I'm pointed is for the TCO badge to match the challenge code background. The abbreviation should match the challenge track - in this case Code.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder I've already finished this one.
ref: https://github.com/appirio-tech/react-components/pull/146
