### ISSUE TITLE
[$20] - New Listings - Keywords not showing full list

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1122]
This appears to still be using mock data.  This needs to be populated from the API.

Please use https://api.topcoder.com/v3/technologies/

**Comment by tladendo** [comment]
@shizhouxing left comment in PR about environments

**Comment by shizhouxing** [comment]
@tladendo Updated.

**Comment by ajefts** [comment]
@shizhouxing  This doesn't seem to be working.

@tladendo Is the latest merged for this?

**Comment by shizhouxing** [comment]
@ajefts It works well here:

![wx20170404-085921](https://cloud.githubusercontent.com/assets/11014212/24637612/1220e422-1915-11e7-87eb-5f4c66e17d31.png)

Please check it again.

**Comment by ajefts** [comment]
@tladendo Can you please check this one?  It's not working in dev:  https://www.topcoder-dev.com/listings/

**Comment by ajefts** [comment]
The api call is being made like this:  https://www.topcoder-dev.com/undefined/technologies/

**Comment by shizhouxing** [comment]
@ajefts That's strange. It works well under both dev and prod here. I can't see the incorrect api call mentioned by you. My own branch used to test it: https://github.com/shizhouxing/react-components/tree/issue-1122.

![screen shot 2017-04-05 at 7 54 39 am](https://cloud.githubusercontent.com/assets/11014212/24683961/39cdfa1c-19d5-11e7-87d1-24f41432d479.png)

**Comment by shizhouxing** [comment]
@ajefts This issue does exist in tom-styling-fixes branch now. But it's caused by @tladendo 's commit : https://github.com/appirio-tech/react-components/commit/4174e0f765ac65ba16ea063f6feef9074f77239f#diff-ae29fea0f0457235ad94a5a060d669fd 

@tladendo It seems `API_URL_V3` doesn't exist as a constant. It's `API_URL` that refers to v3 api. So I think changing `API_URL` to `API_URL_V3` is incorrect here.
