### ISSUE TITLE
[$20] New Listing - My Challenges aren't showing all challenges

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1164]
The My Challenges view in the new listings is not showing all challenges.  Compare to https://www.topcoder.com/my-dashboard/ to see the difference.

**Comment by ajefts** [comment]
@Colinh84 This didn't seem to fix the issue.  I currently have 11 challenges on https://www.topcoder.com/my-dashboard/ and only 8 My Challenges on the listings.

My Dashboard:

![image](https://cloud.githubusercontent.com/assets/3812270/24802040/76054530-1b74-11e7-8a7c-d378852f0763.png)

My Challenges:

![image](https://cloud.githubusercontent.com/assets/3812270/24802080/92e767a0-1b74-11e7-93a9-f4fe967a9587.png)

**Comment by Colinh84** [comment]
@ajefts Do you mind checking this one again? I just tested it from the new dev branch and it still works for me - I have 10 challenges registered and loading the local.topcoder.com/challenges/ URL shows 10 challenges under "My Challenges":

![challenges](https://cloud.githubusercontent.com/assets/2287621/24805635/a93914e6-1bdc-11e7-9d63-f438b533bd60.png)

The changes I made are the only places where the listings page limits the number of challenges to 8, since you only saw 8 in your screenshot, it appears you were possibly on the wrong branch, or maybe accidentally the production site? I noticed sometimes when testing on local.topcoder.com myself, the page will redirect to the www.topcoder.com domain without me noticing.. So just wondering if this could have happened for you.

**Comment by tladendo** [comment]
@ajefts Since this came down to an API issue, should we pay this one out?

**Comment by ajefts** [comment]
Yes, please.  Let's close it out.  It's actually related to private tasks, but let's close this and payout the fix.  Thanks.
