### ISSUE TITLE
[$20] - Copilot designation not showing up on Profile

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#904]
User "ombocorp" is a Studio copilot, shown here: https://community.topcoder.com/tc?module=ViewCopilotPool&size=30&page=5&view=1&sort=12. But his profile does not indicate that he's a copilot (only a designer): https://www.topcoder.com/members/ombocorp/

**Comment by ajefts** [comment]
Note:  This is because the current api/page logic is showing the copilot status based on if they have ever copiloted something as opposed to the profile attribute that says they are a copilot.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru can u assign this to me? Thanks

**Comment by birdofpreyru** [comment]
@shubhendusaurabh you have it.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru created PR #943

**Comment by birdofpreyru** [comment]
@shubhendusaurabh I've merged in your PR, as it solves the issue for the user from the original issue's description, but I leave the issue open for, as I have found, that it is not enough to solve the original problem. E.g. if you look for my profile (I've just become the copilot), I am in the list of copilots here: https://community.topcoder.com/tc?module=ViewCopilotPool&size=30&view=1&sort=0 but both TC API v2, and v3 does not return that I am copilot when my profile is queried. I'd like to wait for more info before deciding what to do with this one.

@ajefts Do you have any ideas, what can be the problem here? Can you tell, which repos host the backend parts related to this copilot and profile reporting?

**Comment by shubhendusaurabh** [comment]
another issue with the API is that it does not return copilot stats, so copilot badge link doesn't work
https://api.topcoder-dev.com/v3/members/ombocorp/stats/

**Comment by birdofpreyru** [comment]
@shubhendusaurabh OK, now I got what is the problem with stats you was referring to, thanks. Let's wait for additional information from @ajefts about the involved backend code, and then we decide what to do with this ticket.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Actually, now it does return `copilot: true` for my profile, should be a caching-related delay in the API. The stats-related issue relates to API, and we don't touch the API for now. Thus this ticket is accepted.
