### ISSUE TITLE
[$20] - "X" to close Badges pop up is too far to the right

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#905]
![image](https://cloud.githubusercontent.com/assets/3812270/21235417/a42879b8-c2c4-11e6-996f-a1414b81c629.png)

**Comment by talesforce** [comment]
This is launched here - https://www.topcoder.com/direct/contest/detail?projectId=30055975

**Comment by ajefts** [comment]
@talesforce The latest is deployed to prod, but I don't see any change for this one.  Can you check?

**Comment by birdofpreyru** [comment]
I'm not sure, how can I add badges to a test user to see it in the locally deployed app. But as you say it has been deployed to prod, I've checked my profile, and it looks it has not been fixed properly. In fact, I see two cross-controls to close the modal, marked red on the screenshot (one of them is barely visible, as it overlays the modal title):

![screenshot-4](https://cloud.githubusercontent.com/assets/20144632/22084700/69dfd940-ddd1-11e6-8fd1-b3a15852a6a4.png)

I also think, it might be better to remove those crosses at all, and to make the modal to close on any click in its empty area?

**Comment by talesforce** [comment]
@ajefts - Not sure if it's a merge issue but I can ask @iversonLv to look at the fix again.

BTW, I agree with the suggestion from @birdofpreyru to remove the x altogether and make the modal close on clicking anywhere outside - that's the simplest user experience.

**Comment by iversonLv** [comment]
will take a look

**Comment by birdofpreyru** [comment]
Thanks. I've checked both. In the first one I still don't quite like the position of the cross. The second one does not work for me, clicking on the empty space does not close the modal.

I'd like to see the following:
1. Move the cross button to the corner of the badges box, as shown in the screenshot (should still close the modal).
2. Ensure, that clicking outside of the badges still closes the modal.
3. Make the area around the badges box more transparent, so that it is more intuitive that clicking there will close the modal.
4. Also, if you look close at the corners of the screen, you'll see that modal shading background has rounded small corners, we don't need them, the background shading should just fill all the viewport without holes.

![screenshot-5](https://cloud.githubusercontent.com/assets/20144632/22110763/2c574e50-de5d-11e6-81f5-4bea4cdcece1.png)

P.S.: In case you are not sure how to mock the badges for testing on the locally deployed App, check my last message here: https://github.com/appirio-tech/topcoder-app/issues/912

P.S.S.: Do you feel like these fixes demand an extra payment? Though I'm now in charge here, I have not yet got any clear instructions, what is my budget, and what are my authorisations in using it. @ajefts @talesforce please help me with this.

**Comment by shizhouxing** [comment]
Hi, I'd like to fix this issue. But I don't have the permission currently. Could you please give me the permission?

**Comment by birdofpreyru** [comment]
@shizhouxing The issue is you to work on it. I don't yet have enough permissions myself to invite you to the repo, so just comment in the issue discussion, to pick it up, or say that it is ready for review.

**Comment by shizhouxing** [comment]
@birdofpreyru Now it's ready for review.
