### ISSUE TITLE
[$60] - Replace "Load More" with infinite scroll

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#906]
On Challenges/Contests (https://www.topcoder.com/my-challenges/?status=completed), after first "Load More," we should switch to infinite scroll, as we do on Member Search

**Comment by talesforce** [comment]
@ajefts - This is included as part of https://www.topcoder.com/direct/contest/detail?projectId=30056070 that has been launched today

**Comment by birdofpreyru** [comment]
I see, this has been pushed into production, but this issue needs further fixes:
1. As of now, the loading of additional portion of past challenges is triggered when the user scrolls to the very end of the currently rendered page. It should be triggered a bit earlier (e.g. when the scrolling approaches the last row of challenges loaded before), so that user experience is smoother.
2. Now, when the scrolling reaches the end of the page, the next loaded portion of challenges has a way more challenges, then initially loaded number of challenges. I believe, equilibrating these will provide a better user experience.
3. The original problem still persists on other pages with listings of challenge, e.g. https://www.topcoder.com/members/birdofpreyru/details/?track=DEVELOP&subTrack=CODE&tab=challenges

**Comment by mhikeo** [comment]
@birdofpreyru I'd like to take up this ticket. Thanks.

**Comment by birdofpreyru** [comment]
@mhikeo You have it :)

**Comment by mhikeo** [comment]
@birdofpreyru Which user has enough data to test?

**Comment by birdofpreyru** [comment]
@mhikeo If you can configure it to work against production database, then my profile has enough challenges in the history to test it.

**Comment by birdofpreyru** [comment]
@mhikeo Any update on this?

**Comment by mhikeo** [comment]
@birdofpreyru I'm releasing this for others to have a look.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru For loading more indicator is it ok to use ripple effect currently being used other pages? Stylingwould feel more consistent.

What no of challenges should be loaded each time? 12?  16?

**Comment by birdofpreyru** [comment]
@shubhendusaurabh If you feel that it looks nice, and more consistent with other places in the site, them I am totally agree for it. My line of thinking is: if scrolling down you reach the end, and you immediately notice that indicator, thus not trying to scroll further when you are supposed to wait, then we are fine. If in that place this indicator is not the first thing, which catches your eyes, then add `Loading more` label next to it, styled the way it fits the place.

> What no of challenges should be loaded each time? 12? 16?

I'll tell you once I play with the result :-D For now, let it be 12, just declare this number like a `CHALLENGES_LOADING_CHUNK` constant in the beginning of the corresponding `.js` file, and place around some comments, that this is the section of code, where all similar constants should be declared, and what does this one, in particular, controls.

**Comment by shubhendusaurabh** [comment]
This is what i meant.
![loading](https://cloud.githubusercontent.com/assets/1818387/22386974/7442a73e-e4ff-11e6-9003-6b52e3ad8f48.png)

**Comment by birdofpreyru** [comment]
@sumansaurabh This looks fine. With this one, probably, no need for labels.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Ok. I accept this one, but still want to comment, that there is a flaw in your implementation (which has no impact now, but it will eventually).

You use the `INFINITE_SCROLL_OFFSET` constant as the fixed offset from the page's bottom to the control point, where you trigger the loading of the next chunk of challenges into the list. This relies on footer's height being constant, which is not true because (1) the footer may be changed through development, and the person who change it, surely will forget to update your `INFINITE_SCROLL_OFFSET` constant; (2) the footer's layout may (and will) become responsive to the page width, thus its height will change if you resize the window, and your implementation does not take it into account.

Thus, the perfect implementation should measure the offset from the bottom of the challenge listing container, so that it does not care about the layout and size of surrounding page elements. Though, as it does not have an impact now, I accept your solution and close the issue. We'll come back to this, once we start having problems with it.
