### ISSUE TITLE
Community overview page not responsive

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#907]

**Comment by talesforce** [comment]
@ajefts - This is included as part of https://www.topcoder.com/direct/contest/detail?projectId=30056070 that has been launched today

**Comment by birdofpreyru** [comment]
@talesforce It looks to me that the issue has been fixed, and the Community Overview page in the production version of TopCoder works fine now. Is there any reason, why this ticket has not been closed?

**Comment by talesforce** [comment]
@birdofpreyru - I did not close the tickets as the PR had not been merged earlier due to some failing tests. As mentioned above, the challenge was  https://www.topcoder.com/direct/contest/detail?projectId=30056070

Feel free to close this and other tickets listed in that challenge if they are working correctly cc @ajefts
