### ISSUE TITLE
Discussion Link on challenge pages

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#914]
Clean up the logic that shows this link.  In certain cases it does not show when it should.

**Comment by birdofpreyru** [comment]
@ajefts Does the challenge details page belongs to this repo? I can find it so far, searching in the code for `Challenge Discussion`, or just `Discussion`.

**Comment by ajefts** [comment]
@birdofpreyru It's actually in this one:  https://github.com/appirio-tech/tc-site

**Comment by birdofpreyru** [comment]
@ajefts

I have revised the code, it looks to me, that the link is working exactly the way it is supposed to: it is shown to a visitor if, and only if he has been registered for a challenge.

In the ticket https://github.com/topcoderinc/cab/issues/31 Nick says:

> If the user hasn't registered for a challenge or the challenge is closed then the "Challenge Discussion"/forum link doesn't show. This makes it difficult to find discussions for closed challenges.

I'd say, whether the challenge is opened or closed has no influence now, the only thing which matters, is whether the visitor is logged in and present in the list of the challenge's registrants. And showing forum link to non-registered users it seems to be what you want to do, because forums may have contain results, which a user is not supposed to have access to if he has not registered (as the registration may include signing additional NDA).

Thus, I need further input on this, or we can close this ticket.
