### ISSUE TITLE
[$10] - Blank Data Science Winner Pages

### ISSUE THREAD

**Issue by vbaileytopcoder** [appirio-tech/topcoder-app#954]
Choose to view winners for any challenge:

https://www.topcoder.com/challenges/data/past/?pageIndex=1

**Comment by birdofpreyru** [comment]
It looks like an easy bug to fix, thus the initial payment is small. I'll increase it, if turns out that the issue is larger that I think now.

The related code is inside https://github.com/appirio-tech/tc-site
It looks that, when loading the winners page, it makes an incorrect call to the backend, which is rejected by the API, thus an error is triggered in the frontend `.js` and the page does not render. I believe, a simple modification of the way the call to the backend is done, should fix this issue.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru Challenge-details page does not support data science challenges. Is there any other link for viewing winners for data science challenges? If not then, we can hide it.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Does the API return necessary data to display the winners for data sci challenges? If so, how difficult will it be to tweak Challenge-details page (or to create a new similar page, for data sci challenges) to show the winners? I'd prefer to find a way to make it work, as of now, I don't see any way at all to see the winners of past data sci challenges, do you see any?

**Comment by shubhendusaurabh** [comment]
@birdofpreyru Data science challenges are bit different from development or design challenges. Like SRM challenges have winners based on `room` and `rating color`. 
Topcoder API docs [http://docs.tcapi.apiary.io/#reference/data/get-algorithm-marathon-challenge-detail/get-algorithm-marathon-detail?console=1] also doesn't mention any relevant API for the same.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Ok. Let's just link those `View` links to these pages `https://community.topcoder.com/longcontest/stats/?module=ViewOverview&rd=16828`. If I am not missing anything, it should make the trick for any marathon match?

**Comment by birdofpreyru** [comment]
@sumansaurabh Do you have any update on it?

**Comment by birdofpreyru** [comment]
@sumansaurabh Sorry, as no news for quite a few days, and no reply now, I'll release this ticket for pickup by other members.
