### ISSUE TITLE
[$20] - Challenge list page's layout is broken on mobile

### ISSUE THREAD

**Issue by MonicaMuranyi** [appirio-tech/topcoder-app#965]
![screenshot_2017-01-28-23-01-46](https://cloud.githubusercontent.com/assets/946461/22399946/834ce556-e5a8-11e6-9ba4-1ccf8b269e82.png)

**Comment by birdofpreyru** [comment]
### Expected Fix

Fix the layout for the mobile screen width. I won't risk to draw the desired result, but the idea is that all control elements above and below the listing (track names, filters, view all, next, links, etc.) should be layed out vertically, one item after another, rather than in horizontal lines, like now.

The challenge listing code belongs to this repo: https://github.com/appirio-tech/tc-site

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Any update?

**Comment by ThomasKranitsas** [comment]
Sorry @birdofpreyru! I'll submit PR later today.

**Comment by birdofpreyru** [comment]
@ThomasKranitsas So?

**Comment by ThomasKranitsas** [comment]
Sorry, I completely forgot about it.. I'll back home at night (my local time zone)... So if anyone wants/CA fix it sooner I'm okay to remove me from this ticket otherwise I'll fix it when I'm back

**Comment by birdofpreyru** [comment]
@ThomasKranitsas So, if you haven't done anything with this yet, I'd say, you can release the ticket, and if it is still open when you have time, you always can pick it up back again.

**Comment by ThomasKranitsas** [comment]
Can you do that as I'm from mobile?

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Well done!

It also looks to me, that the chances are that you are going to be the winner of this Bug Bash, who will take the bonus payment and some TCO points. Can you submit a dummy submission into the original Bug Bash challenge on the TC web site? (I'm not sure yet, whether it is necessary to handle the bonus payment in the optimal way, but let's do it just in case)
