### ISSUE TITLE
[$10] - lists in challenge specs

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#972]
A big complaint has been that unordered and ordered lists do not display correctly on the challenge details pages.  To reproduce, create or edit a challenge in Direct.  Add a list to the details.  View the challenge on the community site.

**Comment by ajefts** [comment]
@birdofpreyru Would love to get a fix for this one if it's not already on the list.

**Comment by birdofpreyru** [comment]
@ajefts It will be done!

Have you seen, we need your help in few issues:

To setup a test challenge in an appeal phase (so that add Complete Appeals / Go to Scorecards buttons into Dashboard, and potentially in challenge details pages):
https://github.com/appirio-tech/topcoder-app/issues/958

Here. I'm still struggling with deployment of the backend code, but it looks like somebody is already ahead me and needs help:
https://github.com/appirio-tech/topcoder-app/issues/917

**Comment by birdofpreyru** [comment]
### Expected Fix
- This should be fixed in the https://github.com/appirio-tech/tc-site repo.
- Here is the test challenge (you can also access it from the locally deployed `tc-site` frontend, which already has some enhacements of the challenged details page, not yet deployed into production): https://www.topcoder.com/challenge-details/30056243/?type=develop&noncache=true Both in the `CHALLENGE OVERVIEW` and `FINAL SUBMISSION GUIDELINES` sections it has sample ordered and un-ordered lists. You should correct their styling.
- In the `CHALLENGE OVERVIEW` section they look this way now:
![scr-5](https://cloud.githubusercontent.com/assets/20144632/22445679/d4828bf0-e748-11e6-8ee3-13850bc607ed.png)
For the unordered (not-numbered) list you should add circular bullets and indentation to list items. Also check that the spacing between list items, and paragraphs inside the list items, are the same as within the surrounding text.
    For the ordered (numbered) list you should fix the spacing between list items to match the inter-paragraph spacing in the surrounding text.
- In the `FINAL SUBMISSION GUIDELINES` section the lists look this way now:
![scr-6](https://cloud.githubusercontent.com/assets/20144632/22445786/5782af94-e749-11e6-8bf5-c5c7c9aad282.png) In addition to the same fixes like in the `CHALLENGE OVERVIEW` section (bullets, indentation, spacing), you should make the font style inside the lists to match that in the surrounding text.
