### ISSUE TITLE
[$5] - Data Science challenge logo missing

### ISSUE THREAD

**Issue by shubhendusaurabh** [appirio-tech/topcoder-app#973]
For some data science challenges logo is missing.
Link: https://www.topcoder.com/challenges/data/active/?pageIndex=1
![logo-broken](https://cloud.githubusercontent.com/assets/1818387/22469215/42afe8f4-e7f1-11e6-93aa-cfe98d182d6b.png)

cc @birdofpreyru

**Comment by birdofpreyru** [comment]
@ajefts The issue is simple: it looks like API can mark data science challenges as TCO-eligible, in this case the frontend attempts to show `banner-tco-data.svg` icon instead of the standard `banner-data.svg`, and there is no such icon.

Do I understand it right, that Data Science challenges are not TCO eligible in the same way, like other challenges? So we should change the frontend to show the standard icon for any datascience challenge? Or, should we add the tco icon for data challenges?

**Comment by birdofpreyru** [comment]
### Expected Fix
Add `wp/wp-content/themes/tcs-responsive/i/banner-tco-data.svg` into the https://github.com/appirio-tech/tc-site repo. Which should be created by adding a small blue/green/yellow stripe to the top of the regular `banner-data.svg`, the same as it is done for other tracks.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru Just noticed that these data science challenges are `Code` type and they work fine when loaded through other routes like `challenges/?pageIndex=2` or `challenges/develop/active/?pageIndex=2`
I think we can simply show develop banner here since they are develop track challenge.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Let's just add the datasci TCO banner. Those banners are `.svg` files, so no need for painting, just copy-pasting of `.svg` code with minor modifications. I am not sure, what is the manager's idea about correct solution to it (probably, they don't want green Code banners to be present on Data Sci listing), so let's make the most simple fix now, and if it is not what is expected, we change further some day later.
